### ISSUE TITLE
96 Hz not working in all modes on S21+ 

### ISSUE THREAD

**Issue by mayurnmahajan** [tribalfs/GalaxyMaxHzPub#161]
**Describe the bug**
The display works at 96 Hz but only in constant high mode (not PSM). As soon as I select adaptive 96 Hz, it stops working.

**To Reproduce**
1. Select refresh rate as 96 Hz in constant high mode (normal only, not working in PSM) and it works.
2. Select maximum limit as 96 Hz in adaptive mode (normal or power saving settings) and it does not work at 96 Hz.

A. GMH version and the exact settings in GMH
Version: 8.1.30
Settings: 
> Adaptive refresh rate mode: 48 Hz to 120 Hz, 48 Hz to 96 Hz, 48 Hz to 60 Hz
> Keep selected mode on PSM: Enabled

**Expected behavior**
Adaptive refresh rate mode working from 48 to 96 Hz in power saving mode.

**Screenshots**
Settings screenshots:
![Screenshot_20240322_053836_Galaxy MaxHz](https://github.com/tribalfs/GalaxyMaxHzPub/assets/71642408/8628796d-e171-457a-a99b-2841e8a09578)
![Screenshot_20240322_053856_Galaxy MaxHz](https://github.com/tribalfs/GalaxyMaxHzPub/assets/71642408/888a6ddd-b56b-4156-8620-81d7ab9a1b3e)
Screen recording of issue: 
https://drive.google.com/file/d/1CSEiqyGlVqDN3ERfKT9eWkJGAsSTJbzG/view?usp=drivesdk

**Smartphone (please complete the following information):**
 - Model Number: SM-S996B/DS
 - OS/OneUI version:  android14 OneUI6
 - Date of latest security update: March 2024
 - Stock or modded ROM: Stock

**Additional context**
None

**Crashlog**
GMH not crashing

**Comment by tribalfs** [comment]
For PSM, [extra steps are required since OneUI5 update on S21+ when rooted.](https://xdaforums.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4220423/)

For 96hz in normal mode, please check [here ](https://xdaforums.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4220423/post-89263399)

**Comment by mayurnmahajan** [comment]
Hi,

Thank you for your response. My device is not rooted.

I have enabled the additional adb permission that was suggested and 120 Hz
does work on power saving mode in adaptive refresh rate mode. However 96 Hz
only works in constant high mode on power saving mode and not adaptive mode
on power saving mode.

I believe it has something to do with the source code. Can you please
suggest why this could be happening?


Thanks & Regards,
Mayur Mahajan

**Comment by mayurnmahajan** [comment]
Hi,

Please check the screen recording using:
*https://drive.google.com/file/d/1EmYWGueP-RrVhcUH-qWZBNE8Pv-3FXAF/view?usp=drivesdk
<https://drive.google.com/file/d/1EmYWGueP-RrVhcUH-qWZBNE8Pv-3FXAF/view?usp=drivesdk>*

What I have noticed the below behaviour:

Normal mode:
1. 96 Hz constant high refresh rate mode is working even at the lowest
brightness
2. 96 Hz adaptive refresh rate mode is not working at all

Power saving mode:
1. 96 Hz constant high refresh rate mode is working at the lowest
brightness
2. 96 Hz adaptive refresh rate mode is not working at all

If 96 Hz can work in constant high refresh rate mode at any brightness
level, I don't see why it couldn't work in adaptive refresh rate mode (I'm
not an app developer, just a software engineer so I have a little
understanding of how it should work.
Please don't get offended or judge me I'm just asking out of curiosity)

Hence, I think that it's not an issue with the missing permission, but
implementation issue. Kindly check and update me on a solution.


Thanks & Best Regards,
Mayur Mahajan

**Comment by tribalfs** [comment]
Try mid level brightness. 
If it is not working, probably samsung disabled it on of its update.

Some mid refresh rates that work in constant mode may **_only work on certain brightness level_** or could be **_disabled_** in adaptive mode due to display calibration issue ( i.e. consistency of gamma curves across the different refresh rates).  Not achieving consistency will cause users to notice flickers on the display when the refresh rate switches specially low brightness conditions.  Human eyes are more sensitive to it on darker environment. The level of brightness varies on how finely the manufacturer has calibrated the display (panel technology is a major factor).  GMH has no control of this.

**Comment by tribalfs** [comment]
Try mid level brightness.
If it is still not working, probably samsung disabled it on one of its update for S21+.

Some mid refresh rates that work in constant mode may only work on certain brightness level or could be disabled in adaptive mode due to display calibration issue ( i.e. consistency of gamma curves across the different refresh rates). Not achieving consistency will cause users to notice flickers on the display when the refresh rate switches specially on low brightness conditions. Human eyes are more sensitive to it on darker environment. The level of brightness varies on how finely the manufacturer has calibrated the display . This is beyond control of GMH.

**Comment by mayurnmahajan** [comment]
Hi Tribalfs/Galaxymaxhzpub,

Thank you for your response. I understand that it is due to hardware
limitations and not an issue with the GMH app.

In this case, is there any way to automatically switch to constant high
mode only in power saving mode?


Thanks & Regards,
Mayur Mahajan
