### ISSUE TITLE
Get error message when installed on Galaxy S22

### ISSUE THREAD

**Issue by og900aero** [tribalfs/GalaxyMaxHzPub#63]
Get error message when installed on Galaxy S22: This app was built for an older version of Android. Im using Android 12.

**Comment by tribalfs** [comment]
[Info:
This app targets older android sdk in order to control refresh rates without ADB setup or root. Just tap OK the dialog that says "This app was built for an older version of Android...." when opened for the first time. If OK button is not visible, just tap the blank space on the lowest portion of the dialog.](https://forum.xda-developers.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4404925/)
