### ISSUE TITLE
One ui 5.0 causes reboot and odd screen layout

### ISSUE THREAD

**Issue by nikc0069** [tribalfs/GalaxyMaxHzPub#67]
**Important: Before submitting a bug, ensure to check [FAQs](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/FREQUENTLY-ASK-QUESTIONS-(FAQs))  and in the app description in the appropriate XDA forum thread for your device to ensure that the behavior is not expected or not part of the limitation of the app.**

**Describe the bug**
On restarting note 20 ultra on android 13/one ui 5.0 the screen seems to render at a high resolution, but the display doesn't change. So only about a quarter of the ui is visible, and then the phone reboots.

**To Reproduce**

A. Version 8.0.0.10, cqhd, adaptive. Lower refresh rate 60, upper 120

B. Steps to reproduce the behavior:
1. Upgrade to one ui 5.0
2. Restart phone
3. Enter pin
4. Wait

**Expected behavior**
Display resolution should change as well as render resolution, so that the phone can be used as normal.

**Smartphone (please complete the following information):**
 - Model Number: SM-N986B/DS
 - OS/OneUI version:  android13 OneUI5. 1
 - Date of latest security update, if applicable: Oct 2022
 - Stock or modded ROM? Stock

**Comment by nikc0069** [comment]
I've now noticed that if you use the Samsung settings ui to switch to fhd before it gmh applies the resolution it seems OK.

**Comment by tribalfs** [comment]
Hi! This is a known [behavior/issue since OneUI4](https://forum.xda-developers.com/t/app-galaxy-max-hz-refresh-rate-mods-screen-off-mods-qs-tiles-tasker-support-and-more.4181447/#:~:text=Caution!!%20Be%20careful%20on%20applying%20CQHD%2B%20on%20Note20Ultra%20with%20OneUI4.*%20%2D%20it%20causes%20the%20UI%20to%20shrink%20after%20reboot%20or%20long%20sleep%20that%20causes%20difficulty%20on%20entering%20the%20lockscreen) [(FAQ#14)](https://github.com/tribalfs/GalaxyMaxHzPub/wiki/Frequently-Asked-Questions-(FAQs)#12-i-cant-see-cqhdcustom-qhd-resolution-option-on-my-note20-ultra-or-s20-series-device).  Unfortunately this is OEM implementation and beyond control of GMH.
